version: '2'

services:
    dante:
        build:
            context: .
            args:
                - PROXY_USERNAME
                - PROXY_PASSWORD
                - PROXY_WORKERS
        ports:
            - ${PROXY_PORT}:1080
        restart: always
