FROM vimagick/dante

ARG PROXY_USERNAME
ARG PROXY_PASSWORD
ARG PROXY_WORKERS

RUN useradd $PROXY_USERNAME
RUN echo $PROXY_USERNAME:$PROXY_PASSWORD | chpasswd

ENV PROXY_WORKERS $PROXY_WORKERS

CMD sockd -f $CFGFILE -p $PIDFILE -N $PROXY_WORKERS
